# -*- coding: utf-8 -*-
"""Random number generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whliJ0pyVR31whHefxVtrHn5egmW3clr

# Let us understand how google is using random number generator using python

1. We take the boundaries(upper and lower limit from the user)
2. We click on generate and it generates a random number
"""

import random
lst=[]
min=int(input("Hey user, enter the lower limit:"))
max=int(input("Hey user, enter the upper limit:"))

for item in range(min,max):
  lst.append(item)

random.choice(lst)

